[package]
name = "dosukoi"
version = "0.2.3"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
dialoguer = "0.11.0"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.0"
